In [1]:
%matplotlib inline
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Nogliki,RU,2021-07-21 14:17:04,51.8333,143.1667,58.14,95,49,7.74
1,1,Kavieng,PG,2021-07-21 14:17:04,-2.5744,150.7967,81.93,79,97,10.16
2,2,Nikolskoye,RU,2021-07-21 14:17:04,59.7035,30.7861,73.40,34,70,9.26
3,3,Nenjiang,CN,2021-07-21 14:17:05,49.1833,125.2167,74.50,88,57,4.21
4,4,Celestun,MX,2021-07-21 14:17:05,20.8667,-90.4000,80.78,78,3,9.42

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [12]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.8)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of wind
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [17]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Kavieng,PG,2021-07-21 14:17:04,-2.5744,150.7967,81.93,79,97,10.16
4,4,Celestun,MX,2021-07-21 14:17:05,20.8667,-90.4000,80.78,78,3,9.42
7,7,Porto Novo,BJ,2021-07-21 14:13:39,6.4965,2.6036,81.75,66,98,11.30
18,18,Georgetown,MY,2021-07-21 14:17:08,5.4112,100.3354,85.95,77,20,4.61
22,22,Ende,ID,2021-07-21 14:17:09,-8.8432,121.6623,75.83,85,46,2.66
26,26,Alim,PH,2021-07-21 14:17:11,9.5649,122.4876,80.51,86,100,12.37
27,27,Jieshi,CN,2021-07-21 14:17:11,22.8134,115.8257,83.95,83,99,6.60
28,28,Cururupu,BR,2021-07-21 14:17:11,-1.8283,-44.8683,86.07,60,61,8.79
29,29,Merritt Island,US,2021-07-21 14:17:11,28.5392,-80.6720,88.09,78,1,5.75
30,30,Muros,ES,2021-07-21 14:17:12,42.7762,-9.0603,75.99,77,71,13.33

In [18]:
preferred_cities_df.count()

City_ID       233
City          233
Country       232
Date          233
Lat           233
Lng           233
Max Temp      233
Humidity      233
Cloudiness    233
Wind Speed    233
dtype: int64

In [20]:
preferred_cities_df = preferred_cities_df.dropna()

In [21]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
1          Kavieng      PG     81.93  -2.5744  150.7967
4         Celestun      MX     80.78  20.8667  -90.4000
7       Porto Novo      BJ     81.75   6.4965    2.6036
18      Georgetown      MY     85.95   5.4112  100.3354
22            Ende      ID     75.83  -8.8432  121.6623
26            Alim      PH     80.51   9.5649  122.4876
27          Jieshi      CN     83.95  22.8134  115.8257
28        Cururupu      BR     86.07  -1.8283  -44.8683
29  Merritt Island      US     88.09  28.5392  -80.6720
30           Muros      ES     75.99  42.7762   -9.0603

In [22]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [26]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
    print("Hotel not found... skipping.")

In [27]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Kavieng,PG,81.93,-2.5744,150.7967,Nusa Island Retreat
4,Celestun,MX,80.78,20.8667,-90.4000,Posada Lilia
7,Porto Novo,BJ,81.75,6.4965,2.6036,Tour Eiffel Hotel Benin
18,Georgetown,MY,85.95,5.4112,100.3354,Cititel Penang
22,Ende,ID,75.83,-8.8432,121.6623,Dwi Putra Hotel - Ende
26,Alim,PH,80.51,9.5649,122.4876,Calamai Tropica
27,Jieshi,CN,83.95,22.8134,115.8257,Yuehai Hotel
28,Cururupu,BR,86.07,-1.8283,-44.8683,POUSADA TRAVÉS'CIA
29,Merritt Island,US,88.09,28.5392,-80.6720,
30,Muros,ES,75.99,42.7762,-9.0603,

In [29]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [31]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [32]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))